package bean;
// Generated 18/10/2022 15:14:45 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Clientes generated by hbm2java
 */
@Entity
@Table(name="clientes"
    ,catalog="db_jheneferlopes"
)
public class Clientes  implements java.io.Serializable {


     private int idcliente;
     private String cpf;
     private String nome;
     private String rg;
     private String orgaoExpeditor;
     private String cidade;
     private String rua;
     private int numero;
     private String bairro;
     private String uf;
     private String cep;
     private String telefone;
     private String email;
     private String ocupacao;
     private String estadoCivil;


    public Clientes() {
    }

	
    public Clientes(int idcliente, String cpf, String nome, String cidade, String rua, String bairro, String uf, String telefone, String email, String estadoCivil) {
        this.idcliente = idcliente;
        this.cpf = cpf;
        this.nome = nome;
        this.cidade = cidade;
        this.rua = rua;
        this.bairro = bairro;
        this.uf = uf;
        this.telefone = telefone;
        this.email = email;
        this.estadoCivil = estadoCivil;
    }
    public Clientes(int idcliente, String cpf, String nome, String rg, String orgaoExpeditor, String cidade, String rua, int numero, String bairro, String uf, String cep, String telefone, String email, String ocupacao, String estadoCivil, Set vendases) {
       this.idcliente = idcliente;
       this.cpf = cpf;
       this.nome = nome;
       this.rg = rg;
       this.orgaoExpeditor = orgaoExpeditor;
       this.cidade = cidade;
       this.rua = rua;
       this.numero = numero;
       this.bairro = bairro;
       this.uf = uf;
       this.cep = cep;
       this.telefone = telefone;
       this.email = email;
       this.ocupacao = ocupacao;
       this.estadoCivil = estadoCivil;

    }
   
     @Id 

    
    @Column(name="idcliente", unique=true, nullable=false)
    public int getIdcliente() {
        return this.idcliente;
    }
    
    public void setIdcliente(int idcliente) {
        this.idcliente = idcliente;
    }

    
    @Column(name="cpf", nullable=false, length=14)
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    
    @Column(name="nome", nullable=false, length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="rg", length=13)
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }

    
    @Column(name="orgao_expeditor", length=4)
    public String getOrgaoExpeditor() {
        return this.orgaoExpeditor;
    }
    
    public void setOrgaoExpeditor(String orgaoExpeditor) {
        this.orgaoExpeditor = orgaoExpeditor;
    }

    
    @Column(name="cidade", nullable=false, length=30)
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }

    
    @Column(name="rua", nullable=false, length=30)
    public String getRua() {
        return this.rua;
    }
    
    public void setRua(String rua) {
        this.rua = rua;
    }

    
    @Column(name="numero")
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }

    
    @Column(name="bairro", nullable=false, length=30)
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    
    @Column(name="uf", nullable=false, length=2)
    public String getUf() {
        return this.uf;
    }
    
    public void setUf(String uf) {
        this.uf = uf;
    }

    
    @Column(name="cep", length=20)
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }

    
    @Column(name="telefone", nullable=false, length=20)
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    
    @Column(name="email", nullable=false, length=25)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="ocupacao", length=20)
    public String getOcupacao() {
        return this.ocupacao;
    }
    
    public void setOcupacao(String ocupacao) {
        this.ocupacao = ocupacao;
    }

    
    @Column(name="estado_civil", nullable=false, length=20)
    public String getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
@Override
public String toString() {
return this.nome;
}



}


