package bean;
// Generated 18/10/2022 15:14:45 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Produto generated by hbm2java
 */
@Entity
@Table(name="produto"
    ,catalog="db_jheneferlopes"
)
public class Produto  implements java.io.Serializable {


     private int codigo;
     private String nome;
     private double valor;
     private String origem;
     private String marca;


    public Produto() {
    }

	
  public Produto(int codigo, String nome, double valor, String marca) {
        this.codigo = codigo;
        this.nome = nome;
        this.valor = valor;
        this.marca = marca;
    }
    public Produto(int codigo, String nome, double valor, String origem, String marca) {
       this.codigo = codigo;
       this.nome = nome;
       this.valor = valor;
       this.origem = origem;
       this.marca = marca;

    }
   
     @Id 

    
    @Column(name="codigo", unique=true, nullable=false)
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="nome", nullable=false, length=20)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="valor", nullable=false, precision=6)
    public double getValor() {
        return this.valor;
    }
    
    public void setValor(double valor) {
        this.valor = valor;
    }

    
    @Column(name="origem", length=15)
    public String getOrigem() {
        return this.origem;
    }
    
    public void setOrigem(String origem) {
        this.origem = origem;
    }

    
    @Column(name="marca", nullable=false, length=15)
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }


public String toString(){
    return getNome();
}

}


