package bean;
// Generated 18/10/2022 15:14:45 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Vendedor generated by hbm2java
 */
@Entity
@Table(name="vendedor"
    ,catalog="db_jheneferlopes"
)
public class Vendedor  implements java.io.Serializable {


     private int matricula;
     private String nome;
     private String cpf;
     private String rg;
     private String tituloEleitor;


    public Vendedor() {
    }

	
  public Vendedor(int matricula, String nome, String cpf, String tituloEleitor) {
        this.matricula = matricula;
        this.nome = nome;
        this.cpf = cpf;
        this.tituloEleitor = tituloEleitor;
    }
    public Vendedor(int matricula, String nome, String cpf, String rg, String tituloEleitor) {
       this.matricula = matricula;
       this.nome = nome;
       this.cpf = cpf;
       this.rg = rg;
       this.tituloEleitor = tituloEleitor;

    }
   
     @Id 

    
    @Column(name="matricula", unique=true, nullable=false)
    public int getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(int matricula) {
        this.matricula = matricula;
    }

    
    @Column(name="nome", nullable=false, length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="cpf", nullable=false, length=14)
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    
    @Column(name="rg", length=11)
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }

    
    @Column(name="titulo_eleitor", nullable=false, length=12)
    public String getTituloEleitor() {
        return this.tituloEleitor;
    }
    
    public void setTituloEleitor(String tituloEleitor) {
        this.tituloEleitor = tituloEleitor;
    }


@Override
public String toString() {
return this.nome;
}

}

