package bean;
// Generated 18/10/2022 15:14:45 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VendasProdutos generated by hbm2java
 */
@Entity
@Table(name="vendas_produtos"
    ,catalog="db_jheneferlopes"
)
public class VendasProdutos  implements java.io.Serializable {


     private int idvendasProdutos;
     private Produto produto;
     private Vendas vendas;
     private int quantidade;
     private double valorunitario;

    public VendasProdutos() {
    }

    public VendasProdutos(int idvendasProdutos, Produto produto, Vendas vendas, int quantidade, double valorunitario) {
       this.idvendasProdutos = idvendasProdutos;
       this.produto = produto;
       this.vendas = vendas;
       this.quantidade = quantidade;

    }
   
     @Id @GeneratedValue (strategy=IDENTITY)

    
    @Column(name="idvendas_produtos", unique=true, nullable=false)
    public int getIdvendasProdutos() {
        return this.idvendasProdutos;
    }
    
    public void setIdvendasProdutos(int idvendasProdutos) {
        this.idvendasProdutos = idvendasProdutos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="produtos", nullable=false)
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idvendas", nullable=false)
    public Vendas getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Vendas vendas) {
        this.vendas = vendas;
    }

    
    @Column(name="quantidade", nullable=false)
    public int getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }

    
    @Column(name="valorunitario", nullable=false, precision=10)
    public double getValorunitario() {
        return this.valorunitario;
    }
    
    public void setValorunitario(double valorunitario) {
        this.valorunitario = valorunitario;
    }




}


