/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telaPrincipalLogin;

import viewVendedor.JDlgVendedor;
import viewCliente.JDlgCliente;

import viewConsultas.JDlgConsultaVendedor;
import viewConsultas.JDlgConsultaProdutos;
import viewConsultas.JDlgConsultaUsuario;
import viewProdutos.JDlgProdutos;
import viewUsuario.JDlgUsuario;
import viewVendas.JDlgVendas;

/**
 *
 * @author jhene
 */
public class JFrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFrmPrincipal
     */
    public JFrmPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Menu");
        setExtendedState(MAXIMIZED_BOTH);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMnuCadastro = new javax.swing.JMenu();
        jMnuVendedor = new javax.swing.JMenuItem();
        jMnuProdutos = new javax.swing.JMenuItem();
        jMnuUsuario = new javax.swing.JMenuItem();
        jMnuCliente = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMnuSair = new javax.swing.JMenuItem();
        jMnuMovimento = new javax.swing.JMenu();
        jMnuVendas = new javax.swing.JMenuItem();
        jMnuConsultas = new javax.swing.JMenu();
        jMnuConsultaFuncionarios = new javax.swing.JMenuItem();
        jMnuConsultaUsuarios = new javax.swing.JMenuItem();
        jMnuConsultaProdutos = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        jMenu4.setText("File");
        jMenuBar3.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar3.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMnuCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jMnuCadastro.setText("Cadrastros ");
        jMnuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuCadastroActionPerformed(evt);
            }
        });

        jMnuVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user32.png"))); // NOI18N
        jMnuVendedor.setText("Vendedor");
        jMnuVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVendedorActionPerformed(evt);
            }
        });
        jMnuCadastro.add(jMnuVendedor);

        jMnuProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/product36.png"))); // NOI18N
        jMnuProdutos.setText("Produtos");
        jMnuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuProdutosActionPerformed(evt);
            }
        });
        jMnuCadastro.add(jMnuProdutos);

        jMnuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/client32.png"))); // NOI18N
        jMnuUsuario.setText("Usuário");
        jMnuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuUsuarioActionPerformed(evt);
            }
        });
        jMnuCadastro.add(jMnuUsuario);

        jMnuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/clients32.png"))); // NOI18N
        jMnuCliente.setText("Cliente");
        jMnuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuClienteActionPerformed(evt);
            }
        });
        jMnuCadastro.add(jMnuCliente);
        jMnuCadastro.add(jSeparator2);

        jMnuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit.png"))); // NOI18N
        jMnuSair.setText("Sair");
        jMnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuSairActionPerformed(evt);
            }
        });
        jMnuCadastro.add(jMnuSair);

        jMenuBar1.add(jMnuCadastro);

        jMnuMovimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/visa.png"))); // NOI18N
        jMnuMovimento.setText("Movimento ");

        jMnuVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produto.png"))); // NOI18N
        jMnuVendas.setText("Vendas");
        jMnuVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVendasActionPerformed(evt);
            }
        });
        jMnuMovimento.add(jMnuVendas);

        jMenuBar1.add(jMnuMovimento);

        jMnuConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jMnuConsultas.setText("Consultas");

        jMnuConsultaFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cliente.png"))); // NOI18N
        jMnuConsultaFuncionarios.setText("Funcionários");
        jMnuConsultaFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuConsultaFuncionariosActionPerformed(evt);
            }
        });
        jMnuConsultas.add(jMnuConsultaFuncionarios);

        jMnuConsultaUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/client32.png"))); // NOI18N
        jMnuConsultaUsuarios.setText("Usuários");
        jMnuConsultaUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuConsultaUsuariosActionPerformed(evt);
            }
        });
        jMnuConsultas.add(jMnuConsultaUsuarios);

        jMnuConsultaProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/product36.png"))); // NOI18N
        jMnuConsultaProdutos.setText("Produtos");
        jMnuConsultaProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuConsultaProdutosActionPerformed(evt);
            }
        });
        jMnuConsultas.add(jMnuConsultaProdutos);

        jMenuBar1.add(jMnuConsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuCadastroActionPerformed
           // TODO add your handling code here:
    }//GEN-LAST:event_jMnuCadastroActionPerformed

    private void jMnuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuClienteActionPerformed
        JDlgCliente jDlgCliente;
        jDlgCliente = new JDlgCliente(this,true);
        jDlgCliente.setVisible(true) ;   // TODO add your handling code here:
    }//GEN-LAST:event_jMnuClienteActionPerformed

    private void jMnuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuProdutosActionPerformed
        JDlgProdutos jDlgProdutos;
        jDlgProdutos = new JDlgProdutos(this,true);
        jDlgProdutos.setVisible(true) ; 
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuProdutosActionPerformed

    private void jMnuVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVendedorActionPerformed
        // TODO add your handling code here:
        JDlgVendedor jDlgVendedor;
        jDlgVendedor = new JDlgVendedor(this,true);
        jDlgVendedor.setVisible(true) ; 
    }//GEN-LAST:event_jMnuVendedorActionPerformed

    private void jMnuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuUsuarioActionPerformed
       JDlgUsuario jDlgUsuario;
        jDlgUsuario = new JDlgUsuario(this,true);
        jDlgUsuario.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuUsuarioActionPerformed

    private void jMnuVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVendasActionPerformed
     JDlgVendas jDlgVendas;
     jDlgVendas = new JDlgVendas(this,true);
     jDlgVendas.setVisible(true);
  
    }//GEN-LAST:event_jMnuVendasActionPerformed

    private void jMnuConsultaProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuConsultaProdutosActionPerformed
JDlgConsultaProdutos jDlgConsultaProdutos;
jDlgConsultaProdutos = new JDlgConsultaProdutos(this,true);
jDlgConsultaProdutos.setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_jMnuConsultaProdutosActionPerformed

    private void jMnuConsultaFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuConsultaFuncionariosActionPerformed
JDlgConsultaVendedor jDlgConsultaFuncionarios;
jDlgConsultaFuncionarios = new JDlgConsultaVendedor(this,true);
jDlgConsultaFuncionarios.setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_jMnuConsultaFuncionariosActionPerformed

    private void jMnuConsultaUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuConsultaUsuariosActionPerformed
JDlgConsultaUsuario jDlgConsultaUsuario;
jDlgConsultaUsuario = new JDlgConsultaUsuario(this,true);
jDlgConsultaUsuario.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_jMnuConsultaUsuariosActionPerformed

    private void jMnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuSairActionPerformed
        setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenu jMnuCadastro;
    private javax.swing.JMenuItem jMnuCliente;
    private javax.swing.JMenuItem jMnuConsultaFuncionarios;
    private javax.swing.JMenuItem jMnuConsultaProdutos;
    private javax.swing.JMenuItem jMnuConsultaUsuarios;
    private javax.swing.JMenu jMnuConsultas;
    private javax.swing.JMenu jMnuMovimento;
    private javax.swing.JMenuItem jMnuProdutos;
    private javax.swing.JMenuItem jMnuSair;
    private javax.swing.JMenuItem jMnuUsuario;
    private javax.swing.JMenuItem jMnuVendas;
    private javax.swing.JMenuItem jMnuVendedor;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
